### ISSUE TITLE
支持更多平台了吗

### ISSUE THREAD

**Issue by jkbwfi** [KevinGong2013/apkgo#1]
希望增加更多平台的方式，多平台上传太苦了

**Comment by KevinGong2013** [comment]
比如说还有哪个平台

**Comment by jkbwfi** [comment]
> 比如说还有哪个平台

华为、小米、三星、应用宝、oppo、vivo、百度、360、魅族、荣耀这些吧😭，是不是很多

**Comment by KevinGong2013** [comment]
360、 应用宝、应用宝、百度 不提供api只能通过网页模拟的方式提交，维护成本太高了直接放弃
魅族、荣耀 这两家后续可以支持一下
三星 others 直接忽略

**Comment by jkbwfi** [comment]
好的，谢谢佬，我可以尝试其他平台用selenium模式方式提交。

还有 [使用手册](https://apkgo.com.cn/) 的网址好像挂掉了。

**Comment by KevinGong2013** [comment]
可以暂时点 `/docs` 目录产看文档

**Comment by DavideStagni** [comment]
# [Dream Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

Exciting news! We're hiring for a Junior Software Developer position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 20, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
Demircivi, @GuitarPlayer-Ma, @viossat, @youcanya, @AngeloStavrow, @tokoyi, @pengzz, @und1e, @aurora, @chavito706, @schwuk, @ddubl, @nicolassrod, @OscarFridh, @gmittal, @andersklenke, @osanaikoutarou, @adam-fowler, @shoichiaizawa, @aznelite89
